name: Release Module

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Name
        id: get-name
        shell: bash
        run: echo "name=$(node ./.github/workflows/get-name.js)" >> $GITHUB_OUTPUT

      - name: Get Version
        id: get-version
        shell: bash
        run: echo "version=$(node ./.github/workflows/get-version.js)" >> $GITHUB_OUTPUT

      - name: Zip Files
        working-directory: ./
        run: zip -r ./${{steps.get-name.outputs.name}}.zip ./*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./${{steps.get-name.outputs.name}}.zip"
          tag_name: ${{steps.get-version.outputs.version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}